-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 14:39:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sitio_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sitio_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sitio_ventas` DEFAULT CHARACTER SET utf8 ;
USE `sitio_ventas` ;

-- -----------------------------------------------------
-- Table `sitio_ventas`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `address` VARCHAR(120) NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio_ventas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  INDEX `person_foreing_key_idx` (`person_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `person_foreing_key`
    FOREIGN KEY (`person_id`)
    REFERENCES `sitio_ventas`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio_ventas`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `session_id` VARCHAR(36) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_foreign_key_idx` (`user_id` ASC),
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC),
  CONSTRAINT `user_foreign_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `sitio_ventas`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio_ventas`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(120) NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `product_user_foreign_key_idx` (`user_id` ASC),
  CONSTRAINT `product_user_foreign_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `sitio_ventas`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio_ventas`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `message` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `message_person_foreign_key_idx` (`person_id` ASC),
  CONSTRAINT `message_person_foreign_key`
    FOREIGN KEY (`person_id`)
    REFERENCES `sitio_ventas`.`people` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio_ventas`.`shopping_carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`shopping_carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `finished` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `shopping_cart_user_foreign_key_idx` (`user_id` ASC),
  CONSTRAINT `shopping_cart_user_foreign_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `sitio_ventas`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sitio_ventas`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sitio_ventas`.`items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `item_cart_foreign_key_idx` (`cart_id` ASC),
  INDEX `item_product_foreign_key_idx` (`product_id` ASC),
  CONSTRAINT `item_cart_foreign_key`
    FOREIGN KEY (`cart_id`)
    REFERENCES `sitio_ventas`.`shopping_carts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `item_product_foreign_key`
    FOREIGN KEY (`product_id`)
    REFERENCES `sitio_ventas`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
